"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Shape_1 = require("./Shape");
var Circle_1 = require("./Circle");
var Rectangle_1 = require("./Rectangle");
var shape = new Shape_1.Shape(10, 20);
console.log(shape.getInfo());
var circle = new Circle_1.Circle(5, 10, 20);
console.log(circle.getInfo());
var rect = new Rectangle_1.Rectangle(10, 20, 30, 40);
console.log(rect.getInfo());
